fix ci

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -45,13 +45,12 @@ jobs:
         run: |
           expected_checksum="${{ env.LATEX_EXPECTED_CHECKSUM }}"
           actual_checksum=$(docker inspect --format='{{.RepoDigests}}' ${{ env.LATEX_DOCKER_IMAGE_NAME }}:${{ env.LATEX_DOCKER_IMAGE_TAG }} | sha256sum | awk '{print $1}')
-          
+
           if [ "$expected_checksum" != "$actual_checksum" ]; then
             echo "Error: Docker image checksum mismatch."
             exit 1
           fi
 
-      
       - name: Convert from .cook to markdown
         run: |
           # first ensure we have all webp images, ideally this runs locally but best to have it here too
@@ -61,16 +60,16 @@ jobs:
 
           # sync all remaining images, for steps etc
           rsync -av --ignore-existing --include "*/" --include="*.webp"  --exclude="*" cook/ docs/
-      
+
       - name: Make gallery
         run: |
           # use script to make first page
           python .github/gallery.py docs abc >> docs/index.md
 
       - name: Build Webpage with mkdocs
-        run : |
+        run: |
           mkdocs build -c
-      
+
       - name: Compile latex to .pdf
         uses: xu-cheng/latex-action@v3
         with:
@@ -86,11 +85,39 @@ jobs:
           SSHUSER: githubci
           SSHPORT: ${{ secrets.PORT }}
         run: |
-          IPADDR=$(nslookup -q=A ${SERVER} 9.9.9.9 | grep -Eo 'Address: [^ ]+$' | tail -1 | awk '{print $2}') 
+          IPADDR1=$(nslookup -q=A ${SERVER} 9.9.9.9 | grep -Eo 'Address: [^ ]+$' | tail -1 | awk '{print $2}') 
           IPADDR2=$(dig @1.1.1.1 ${SERVER} | grep '^;; ANSW' -A 1  | tail -n 1 | cut -f 5)
-          echo "nslooup at 9.9.9.9: $IPADDR"
+          echo "nslooup at 9.9.9.9: $IPADDR1"
           echo "dig at 1.1.1.1: $IPADDR2"
-          
+
+          # check if IPADDR is an ipv4 address
+          # function
+          function valid_ip()
+          {
+            local  ip=$1
+            local  stat=1
+
+            if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+              OIFS=$IFS
+              IFS='.'
+              ip=($ip)
+              IFS=$OIFS
+              [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
+                && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
+              stat=$?
+            fi
+            return $stat
+          }
+
+          if valid_ip $IPADDR1; then
+            IPADDR=$IPADDR1
+          elif valid_ip $IPADDR2; then
+            IPADDR=$IPADDR2
+          else
+            echo "Error: Could not resolve IP address"
+            exit 1
+          fi
+
           echo "${SSHKEY}" > .key; 
           chmod 600 .key;
           rsync -avvvz -e "ssh -i .key -o StrictHostKeyChecking=no -p ${SSHPORT}" site ${SSHUSER}@${IPADDR2}:/home/githubci/webspace/recipes/
